@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkAttendanceCommandParser" as MarkAttendanceCommandParser LOGIC_COLOR
participant "a:MarkAttendanceCommand" as MarkAttendanceCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "s:Student" as Student MODEL_COLOR
participant "al:AttendanceList" as AttendanceList MODEL_COLOR
end box

[-> LogicManager : execute("markattendance n/\"John Tan\" s/Math l/L1 st/Present")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("markattendance n/\"John Tan\" s/Math l/L1 st/Present")
activate AddressBookParser

create MarkAttendanceCommandParser
AddressBookParser -> MarkAttendanceCommandParser
activate MarkAttendanceCommandParser

MarkAttendanceCommandParser -> MarkAttendanceCommandParser : tokenize(args)
activate MarkAttendanceCommandParser
MarkAttendanceCommandParser --> MarkAttendanceCommandParser : extract name, subject, lesson, status
deactivate MarkAttendanceCommandParser

create MarkAttendanceCommand
MarkAttendanceCommandParser -> MarkAttendanceCommand : new MarkAttendanceCommand(name, subject, lesson, status)
activate MarkAttendanceCommand
MarkAttendanceCommand --> MarkAttendanceCommandParser : a
deactivate MarkAttendanceCommand

MarkAttendanceCommandParser --> AddressBookParser : a
deactivate MarkAttendanceCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> MarkAttendanceCommand : execute(model)
activate MarkAttendanceCommand

MarkAttendanceCommand -> Model : getFilteredPersonList()
activate Model
Model --> MarkAttendanceCommand : List<Person>
deactivate Model

MarkAttendanceCommand -> MarkAttendanceCommand : find student by name
MarkAttendanceCommand -> Student : (cast) Student
activate Student

MarkAttendanceCommand -> Student : getSubjects()
Student --> MarkAttendanceCommand : List<Subject>

MarkAttendanceCommand -> MarkAttendanceCommand : check if subject enrolled?
alt Not Enrolled
    MarkAttendanceCommand --> LogicManager : throw CommandException("Student not enrolled")
    deactivate Student
    deactivate MarkAttendanceCommand
    deactivate LogicManager
    return
end

MarkAttendanceCommand -> Model : hasLesson(new Lesson(lessonName, subject.name))
activate Model
Model --> MarkAttendanceCommand : true
deactivate Model

MarkAttendanceCommand -> Student : getAttendanceList()
Student --> MarkAttendanceCommand : al:AttendanceList

MarkAttendanceCommand -> AttendanceList : markAttendance(Lesson, Status)
activate AttendanceList
AttendanceList --> MarkAttendanceCommand : updated/created record
deactivate AttendanceList

create ":CommandResult" as CommandResult
MarkAttendanceCommand -> CommandResult : new CommandResult(successMessage)
activate CommandResult
CommandResult --> MarkAttendanceCommand : result
deactivate CommandResult

MarkAttendanceCommand --> LogicManager : result
deactivate MarkAttendanceCommand

[<-- LogicManager : result
deactivate LogicManager
@enduml