@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Student
Class CurrentStudentList
Class ArchivedStudentList
Class Address
Class Email
Class Name
Class Phone
Class Tag

Class Subject
Class LessonList
Class Lesson
Class AttendanceList
Class AttendanceRecord
Class AttendanceStatus

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" CurrentStudentList : currentStudents
AddressBook *--> "1" ArchivedStudentList : archivedStudents

CurrentStudentList *--> "*" Student : students
ArchivedStudentList *--> "*" Student : students

Person <|-- Student
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

Student *--> "1..*" Subject : subjects
Student *--> "1" AttendanceList
AttendanceList *--> "*" AttendanceRecord

StudentList *--> "*" Student : students
StudentList --> "1" Subject : subject

AttendanceRecord --> "1" Lesson
AttendanceRecord .right.> AttendanceStatus : status

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

Subject --> LessonList
LessonList -> Lesson

ModelManager --> "~* filtered" Person
ModelManager --> "~* filtered" Person : archivedPersons
@enduml
